name: Build Legacy S812 (SLAzurin)
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04 # Older runner for better compatibility with 2024/2025 legacy code
    steps:
      - name: Maximize Disk Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Checkout SLAzurin Fork
        uses: actions/checkout@v4
        with:
          repository: SLAzurin/build-armbian-custom
          ref: s8xx-2025-02-27 # The exact branch
          path: build

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git qemu-user-static rsync

      - name: Execute Build
        run: |
          cd build
            ./compile.sh BOARD=aml-s812 BRANCH=current RELEASE=bookworm BUILD_MINIMAL=yes BUILD_DESKTOP=no

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: S812-Legacy-Image
          path: build/output/images/*.img.xz
